export const mockTrendingTech = [
  { name: "AI Agents", score: 98, growth: "+142%", category: "AI", color: "#6366f1" },
  { name: "MCP Servers", score: 94, growth: "+118%", category: "AI", color: "#0891b2" },
  { name: "LangGraph", score: 89, growth: "+96%", category: "AI", color: "#059669" },
  { name: "Vector Databases", score: 87, growth: "+88%", category: "Data", color: "#d97706" },
  { name: "RAG Systems", score: 85, growth: "+76%", category: "AI", color: "#dc2626" },
  { name: "Multimodal AI", score: 82, growth: "+71%", category: "AI", color: "#7c3aed" },
  { name: "Edge AI", score: 78, growth: "+64%", category: "AI", color: "#0d9488" },
  { name: "OpenAI Realtime API", score: 76, growth: "+59%", category: "API", color: "#ea580c" },
  { name: "Rust", score: 73, growth: "+47%", category: "Language", color: "#4f46e5" },
  { name: "Bun.js", score: 70, growth: "+43%", category: "Runtime", color: "#db2777" },
];

export const mockNewsArticles = [
  {
    id: "1",
    title: "OpenAI Releases GPT-4o Realtime API for Voice and Vision",
    source: "TechCrunch",
    publishedAt: "2h ago",
    url: "#",
    impact: 95,
    tags: ["OpenAI", "Realtime API", "Multimodal"],
    summary: "OpenAI's latest API enables real-time voice and vision capabilities, transforming how AI agents interact with users in production environments.",
    category: "AI",
    imageUrl: null,
  },
  {
    id: "2",
    title: "AWS and Google Cloud Announce Open-Source AI Agent Frameworks",
    source: "TechCrunch",
    publishedAt: "4h ago",
    url: "#",
    impact: 92,
    tags: ["Cloud AI", "AI Agents", "Open Source"],
    summary: "Major cloud providers are introducing open-source AI agent orchestration frameworks to support scalable, multi-agent enterprise deployments.",
    category: "Cloud",
    imageUrl: null,
  },
  {
    id: "3",
    title: "LangGraph 0.3 Drops: Cyclic Reasoning Graphs Now Production-Ready",
    source: "The Verge",
    publishedAt: "6h ago",
    url: "#",
    impact: 88,
    tags: ["LangGraph", "LangChain", "AI Agents"],
    summary: "LangGraph's latest release brings stability and performance improvements, making cyclic AI reasoning graphs enterprise-ready.",
    category: "AI",
    imageUrl: null,
  },
  {
    id: "4",
    title: "MCP Protocol Hits 500+ Community Servers — Ecosystem Explodes",
    source: "Hacker News",
    publishedAt: "8h ago",
    url: "#",
    impact: 91,
    tags: ["MCP", "Anthropic", "AI Tooling"],
    summary: "The Model Context Protocol ecosystem reaches a major milestone with 500+ community servers enabling agents to access any data source.",
    category: "AI",
    imageUrl: null,
  },
  {
    id: "5",
    title: "GitHub Copilot Workspace Goes GA — AI-Powered Dev Environments",
    source: "GitHub Blog",
    publishedAt: "12h ago",
    url: "#",
    impact: 85,
    tags: ["GitHub", "Copilot", "Dev Tools"],
    summary: "GitHub Copilot Workspace reaches general availability, letting developers describe tasks in natural language and letting AI plan and implement changes.",
    category: "Dev Tools",
    imageUrl: null,
  },
  {
    id: "6",
    title: "Rust Overtakes Java in Developer Satisfaction for 3rd Year Running",
    source: "Stack Overflow",
    publishedAt: "1d ago",
    url: "#",
    impact: 72,
    tags: ["Rust", "Programming", "Survey"],
    summary: "Stack Overflow's annual survey confirms Rust remains the most-loved language, with growing adoption in systems programming and WebAssembly.",
    category: "Language",
    imageUrl: null,
  },
];

export const mockTechStackChart = [
  { tech: "AI Agents", mentions: 4820, prev: 2100 },
  { tech: "MCP", mentions: 3910, prev: 820 },
  { tech: "LangGraph", mentions: 3240, prev: 1400 },
  { tech: "RAG", mentions: 2980, prev: 1850 },
  { tech: "Vector DBs", mentions: 2750, prev: 1600 },
  { tech: "Next.js", mentions: 2540, prev: 2100 },
  { tech: "Rust", mentions: 2310, prev: 1780 },
  { tech: "Multimodal AI", mentions: 2180, prev: 750 },
  { tech: "Edge AI", mentions: 1940, prev: 620 },
  { tech: "WebAssembly", mentions: 1720, prev: 1250 },
];

export const mockHNStories = [
  { id: 1, title: "Show HN: I built an MCP server that gives AI access to my entire Notion workspace", points: 842, comments: 234, time: "3h" },
  { id: 2, title: "Why Model Context Protocol (MCP) is the HTTP of the Agentic Age", points: 671, comments: 189, time: "5h" },
  { id: 3, title: "LangGraph vs CrewAI vs AutoGen: A comprehensive comparison in 2025", points: 543, comments: 167, time: "7h" },
  { id: 4, title: "Why RAG is not enough — the case for Knowledge Graphs in AI systems", points: 489, comments: 134, time: "9h" },
  { id: 5, title: "OpenAI Realtime API deep-dive: latency, cost, and production considerations", points: 412, comments: 98, time: "11h" },
];
